name: Slack CI-lint

on:
  push:
    branches: [ "feature/slack-b" ]
  pull_request:

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”­Checkout code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: â¬ Install Ruff
        run: pip install ruff

      - name: âœ…Run Ruff Check
        run: ruff check .

      - name: â†”ï¸ Run Ruff Format
        run: ruff format .
