name: Slack CI-tests

on:
  push:
    branches: [ "feature/slack-b" ]
  pull_request:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout repository
        uses: actions/checkout@v4

      - name:  âš’ï¸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: â¬ Install dependencies
        run: pip install -r src/requirements.txt

      - name: âœ… Run tests
        run: pytest -v src
